---
# Kubelet will not start with swap enabled
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: add memory cgroup config to boot params
  replace:
    path: /boot/firmware/nobtcmd.txt
    regexp: '(fixrtc)$'
    replace: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  notify: reboot server

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

# Ubuntu 19.04+ uses a newer version of iptables which is incompatible
# with the kubelet.
- name: Install legacy iptables
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - iptables 
      - arptables
      - ebtables

- name: Set legacy iptables versions
  alternatives:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  vars:
    links:
      - name: iptables
        path: /usr/sbin/iptables-legacy
      - name: ip6tables
        path: /usr/sbin/ip6tables-legacy
      - name: arptables
        path: /usr/sbin/arptables-legacy
      - name: ebtables
        path: /usr/sbin/ebtables-legacy
  with_items:
    - "{{ links }}"

- name: Install Kubernetes binaries
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet=1.17.2-00
      - kubeadm=1.17.2-00
      - kubectl=1.17.2-00

- name: Configure node ip
  lineinfile:
    create: yes
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_default_ipv4.address }}

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
